# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17FWv4fDEarMcPNZDsEaHm1YC4qOlYQ3X
"""

import os
import csv
import json

class FileManager:
    def __init__(self, filename):
        self.filename = filename

    def check_file(self):
        print("Checking file...")
        if os.path.exists(self.filename):
            print(f"File found: {self.filename}")
            return True
        print(f"Error: {self.filename} not found!")
        return False

    def create_output_folder(self, folder='output'):
        print("Checking output folder...")
        if not os.path.exists(folder):
            os.makedirs(folder)
            print(f"Output folder created: {folder}/")
        else:
            print(f"Output folder already exists: {folder}/")

class DataLoader:
    def __init__(self, filename):
        self.filename = filename
        self.students = []

    def load(self):
        print("Loading data...")
        try:
            with open(self.filename, mode='r', encoding='utf-8') as f:
                self.students = list(csv.DictReader(f))
                print(f"Data loaded: {len(self.students)} students")
                return self.students
        except FileNotFoundError:
            print("CSV file not found!")
            return []

    def preview(self, n=5):
        print(f"First {n} rows:")
        print("-" * 40)
        for s in self.students[:n]:
            gpa = s.get('GPA') or s.get('gpa')
            print(f"{s['student_id']} | {s['age']} | {s['country']} | GPA: {gpa}")
        print("-" * 40)

class DataAnalyser:
    def __init__(self, students):
        self.students = students
        self.result = {}

    def analyse(self):
        counts = {}
        for s in self.students:
            country = s['country']
            counts[country] = counts.get(country, 0) + 1

        top_3_list = sorted(counts.items(), key=lambda x: x[1], reverse=True)[:3]

        self.result = {
            "analysis": "Country Analysis",
            "total_students": len(self.students),
            "total_countries": len(counts),
            "top_3": [{"country": c, "count": n} for c, n in top_3_list],
            "all_countries": counts
        }
        return self.result

    def print_results(self):
        print("\n--- ANALYSIS RESULT ---")
        print(f"Countries found: {self.result['total_countries']}")
        print("Top 3:")
        for i, item in enumerate(self.result['top_3'], 1):
            print(f"{i}. {item['country']} ({item['count']} students)")
        print("-----------------------")

class ResultSaver:
    def __init__(self, result, output_path):
        self.result = result
        self.output_path = output_path

    def save_json(self):
        try:
            with open(self.output_path, 'w', encoding='utf-8') as f:
                json.dump(self.result, f, indent=4)
            print(f"Success! Saved to {self.output_path}")
        except Exception as e:
            print(f"Save error: {e}")

def main():
    file_name = 'students.csv'

    fm = FileManager(file_name)
    if not fm.check_file():
        return

    fm.create_output_folder()

    loader = DataLoader(file_name)
    loader.load()
    loader.preview()

    analyser = DataAnalyser(loader.students)
    analyser.analyse()
    analyser.print_results()

    saver = ResultSaver(analyser.result, 'output/result.json')
    saver.save_json()

if __name__ == "__main__":
    main()

    import csv

data = [
    ['student_id', 'age', 'gender', 'country', 'GPA', 'class_attendance_percent'],
    ['S00001', '23', 'Female', 'Germany', '3.81', '95'],
    ['S00002', '26', 'Female', 'USA', '3.46', '88'],
    ['S00003', '18', 'Female', 'Canada', '4.0', '92'],
    ['S00004', '20', 'Male', 'Australia', '3.77', '85'],
    ['S00005', '28', 'Female', 'Australia', '4.0', '98']
]

with open('students.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerows(data)

print("Файл students.csv успешно создан!")